import pymongo as mdb
import slippi as slp

def group_will_get_hit(db, characters, time):
    group=db.frames.aggregate([
                        {"$match":{
                                "$or":[{
                                "players.0.character":characters[0], 
                                "players.1.character":characters[1], 
                                "players.0.will_get_hit_by.time":time},
                                {"players.1.character":characters[0], 
                                "players.0.character":characters[1], 
                                "players.1.will_get_hit_by.time":time}]
                        }},
                        {"$project":{"data":{"$cond":{
                            "if":{"$eq":[characters[0],{"$arrayElemAt":["$players.character",0]}]},
                                "then":{
                                        "will_get_hit_by":{"$arrayElemAt":["$players.will_get_hit_by.move",0]},
                                        "count":{"$sum":1},
                                        "state_1":{"$arrayElemAt":["$players.state",0]},
                                        "state_2":{"$arrayElemAt":["$players.state",1]},
                                        "position_1":{"$arrayElemAt":["$players.position",0]},
                                        "position_2":{"$arrayElemAt":["$players.position",1]},
                                        "relative_position":{"$arrayElemAt":["$players.relative_position",0]},
                                        "damage_1":{"$arrayElemAt":["$players.damage",0]},
                                        "damage_2":{"$arrayElemAt":["$players.damage",1]},
                                        "shield_size":{"$arrayElemAt":["$players.shield_size",0]},
                                        "speed_1":{"$arrayElemAt":["$players.speed",0]},
                                        "speed_2":{"$arrayElemAt":["$players.speed",1]},
                                        "hitstun":{"$arrayElemAt":["$players.hitstun",0]}},
                            "else":{
                                "$cond":{
                                    "if":{"$eq":[characters[0],{"$arrayElemAt":["$players.character",1]}]},
                                    "then":{
                                        "will_get_hit_by":{"$arrayElemAt":["$players.will_get_hit_by.move",1]},
                                        "count":{"$sum":1},
                                        "state_1":{"$arrayElemAt":["$players.state",1]},
                                        "state_2":{"$arrayElemAt":["$players.state",0]},
                                        "position_1":{"$arrayElemAt":["$players.position",1]},
                                        "position_2":{"$arrayElemAt":["$players.position",0]},
                                        "relative_position":{"$arrayElemAt":["$players.relative_position",1]},
                                        "damage_1":{"$arrayElemAt":["$players.damage",1]},
                                        "damage_2":{"$arrayElemAt":["$players.damage",0]},
                                        "shield_size":{"$arrayElemAt":["$players.shield_size",1]},
                                        "speed_1":{"$arrayElemAt":["$players.speed",1]},
                                        "speed_2":{"$arrayElemAt":["$players.speed",0]},
                                        "hitstun":{"$arrayElemAt":["$players.hitstun",1]}},
                                    "else":None}
                                }
                            }}
                        }},
                        {"$group":{
                            "_id":{"will_get_hit_by":"$data.will_get_hit_by"},
                            "count":{"$sum":"$data.count"},
                            "state_1":{"$push":"$data.state_1"},
                            "state_2":{"$push":"$data.state_2"},
                            "position_1":{"$push":"$data.position_1"},
                            "position_2":{"$push":"$data.position_2"},
                            "relative_position":{"$push":"$data.relative_position"},
                            "damage_1":{"$push":"$data.damage_1"},
                            "damage_2":{"$push":"$data.damage_2"},
                            "shield_size":{"$push":"$data.shield_size"},
                            "speed_1":{"$push":"$data.speed_1"},
                            "speed_2":{"$push":"$data.speed_2"},
                            "hitstun":{"$push":"$data.hitstun"}}
                        },
                        {"$project":{
                            "_id":0,
                            "will_get_hit_by":"$_id.will_get_hit_by",
                            "character_1":characters[0],
                            "character_2":characters[1],
                            "frames_to_hit":str(time),
                            "count":1,
                            "state_1":1,
                            "state_2":1,
                            "position_1":1,
                            "position_2":1,
                            "relative_position":1,
                            "damage_1":1,
                            "damage_2":1,
                            "shield_size":1,
                            "speed_1":1,
                            "speed_2":1,
                            "hitstun":1}
                        }
                    ], allowDiskUse=True)
    db.stats.insert_many(group)